# Generated by Django 2.0.2 on 2018-03-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_permission', models.CharField(choices=[('ADD', 'ADDNEW'), ('EDIT', 'EDIT'), ('DEL', 'DELETE')], max_length=4)),
                ('group_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('role_permission', models.CharField(choices=[('ADMIN', 'ADMIN'), ('PUBLISHER', 'PUBLISHER'), ('APPROVER', 'APPROVER'), ('MODERATOR', 'MODERATOR'), ('EDITOR', 'EDITOR'), ('CREATOR', 'CREATOR')], max_length=10)),
                ('role_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('fullname', models.CharField(default=0, max_length=201)),
                ('password', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('hobbies', models.TextField()),
                ('user_desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(to='myapp.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(to='myapp.User'),
        ),
    ]
